{
 "title": "Dashboard Flagger",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Primário vs Canário",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flagger_canary_weight", "legendFormat": "Primário vs Canário" }
   ]
  },
  {
   "title": "Duração do Processo de Deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flagger_canary_duration_seconds_count",
     "legendFormat": "Duração do Canário"
    }
   ]
  },
  {
   "title": "Porcentagem da Versão Primária",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flagger_canary_weight{workload=\"podinfo-primary\", namespace=\"test\"}",
     "legendFormat": "Porcentagem Primário"
    }
   ]
  },
  {
   "title": "Porcentagem da Versão Canário",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flagger_canary_weight{workload=\"podinfo\", namespace=\"test\"}",
     "legendFormat": "Porcentagem Canário"
    }
   ]
  }
 ]
}